services:
  - type: web
    name: portfolio-lk
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://portfolio-lk-six.vercel.app
      - key: MONGODB_URI
        sync: false          # set manually in Render dashboard
      - key: RESEND_API_KEY
        sync: false          # set manually in Render dashboard
      - key: EMAIL_TO
        value: leonardsengoma07@gmail.com
